#!/bin/bash
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /21051247/clone ensure=absent force=true
puppet resource file /21051247 ensure=directory
puppet resource file /21051247/clone ensure=directory
cd /21051247/clone
git clone https://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@github.com/wander3010/operate_repo.git
cp -p /21051247/clone/operate_repo/index.html /var/www/html
